// -------------------------------------------------------------------------
// main.cpp - main driver of the Finite element AnalisyS Tool (FAST).
// -------------------------------------------------------------------------
// Created:      21-Apr-2011     Evandro Parente Junior
//
// Modified:     23-Jun-2011     Evandro Parente Junior
//               Creation of Feedback flag.
//
// Modified:     08-Apr-2015     Elias Saraiva Barroso
//               Input/output operations using c++ streams.
//
// Modified:     16-Jun-2015     Elias Saraiva Barroso
//               Stolen the wall clock meter from BIOS and added on FAST.
// -------------------------------------------------------------------------

#include <time.h>
#include <string>
#include <iostream>
#include <iomanip>
#include <fstream>
#include <string>

using namespace std;

#include "input.h"
#include "ctrl.h"
#include "utl.h"
#include "gbldef.h"
#include "shpiga.h"

typedef long double tClock;

const string Version("2.4.4 - Dec/2025");

// -------------------------------------------------------------------------
// Global variables:
//
ifstream in;
ofstream out, outem;
string   fname;
bool Feedback = true;
bool Printing = false;

// -------------------------------------------------------------------------
// main function:
//
int main(int argc, char **argv)
{
  // Disable syncronization between ios and stdio to increase performance.

  ios_base::sync_with_stdio(false);

  // Load IGA libraries.

  InitIGA( );

  // Get program options (feedback).

  if (argc > 2 && string(argv[2]) == "-silent") Feedback = false;

  if (Feedback)
  {
    cout << "\n";
    cout << "\t===================================================================\n";
    cout << "\t==                                                               ==\n";
    cout << "\t==               Finite element AnalisyS Tool - FAST             ==\n";
    cout << "\t==                                                               ==\n";
    cout << "\t==               Version " << left << setw(37) << Version << "   ==\n";
    cout << "\t==                                                               ==\n";
    cout << "\t==  Laboratorio de Mecanica Computacional e Visualizacao - LMCV  ==\n";
    cout << "\t==                                                               ==\n";
    cout << "\t==            Universidade Federal do Ceara - UFC                ==\n";
    cout << "\t==                                                               ==\n";
    cout << "\t===================================================================\n\n";
  }

  // Get the name of the input file.

  if (argc == 1)
  {
    cout << "\n\tEnter the input file name [.dat]......... ";
    cin >> fname;
  }
  else
    fname = string(argv[1]);

  // Start time counter.

  tClock cputime = clock( );
  time_t start = time(NULL);

  // Open the input file.

  string aux = fname + ".dat";
  in.open(aux.c_str());
  if (!in.is_open())
  {
    cout << "Invalid input file." << "\n";
    return(1);
  }

  // Open the output file.

  aux = fname + ".pos";
  out.open(aux.c_str());
  if (!out.is_open())
  {
    cout << "Invalid output file." << "\n";
    return(1);
  }

  out << "%HEADER\n";
  out << "Output file generated by FAST " << Version << ".\n";

  // Read the input data and close the input file.

  if (Feedback)
    cout << "\n\tReading the input data .................." << endl;
  InpReadData( );
  InpCopyData( );
  in.close( );

  // Compute the nodal equations and the matrix profile.

  if (Feedback)
    cout << "\n\tComputing the nodal equations ..........." << endl;

  cControl :: Init( );
  cControl *ctrl = cControl :: GetControl( );
 
  // Process the analysis and print the output data.

  ctrl->Solver( );

  // Destroy the model, write end mark and close the output file.

  cControl :: End( );
  out.close( );
  if (outem.is_open( ))
    outem.close( );

  // Print the total elapsed time.

  time_t end = time(NULL);
  double diff = difftime(end,start);
  cputime = clock( ) - cputime;
  if (Feedback) 
  {
    cout << endl << "\t\tCPU time: " << fixed << setprecision(4); 
    cout << (double)(cputime/CLOCKS_PER_SEC) << " (s)" << endl;
    cout << endl << "\t\tWall clock: " << diff << " (s)" << endl; 
  }

  return(0);
}
	 
// ======================================================= End of file =====
